# Generated by Django 3.2.20 on 2023-08-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230815_1242'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='album',
            name='Это название уже занято',
        ),
    ]
