# Generated by Django 3.2.20 on 2023-08-15 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_remove_album_это название уже занято'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('title', 'author')},
        ),
    ]
