# Generated by Django 3.2.20 on 2023-08-15 12:26

import api.validator.file_size
import django.core.validators
from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_album_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to=garpix_utils.file.file_field.get_file_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg']), api.validator.file_size.FileSizeValidator(5242880)], verbose_name='Изображение'),
        ),
    ]
