# Generated by Django 3.2.20 on 2023-08-16 14:00

from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Миниатюрное изображение'),
        ),
    ]
