# Generated by Django 3.2.20 on 2023-08-17 09:41

from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_album_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Миниатюрное изображение'),
        ),
    ]
