# Generated by Django 3.2.20 on 2023-08-24 08:22

from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_topalbums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topalbums',
            name='webm_file',
            field=models.FileField(max_length=200, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Топ-10 просматриваемых фото'),
        ),
    ]
