# Generated by Django 3.2.20 on 2023-08-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Обратная связь')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Обратная связь')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='systemnotify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Обратная связь')], null=True, verbose_name='Событие'),
        ),
    ]
