# Generated by Django 3.2.20 on 2023-08-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0004_auto_20230814_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Топ-3 самых просматриваемых фотографий на сайте')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Топ-3 самых просматриваемых фотографий на сайте')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='systemnotify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Топ-3 самых просматриваемых фотографий на сайте')], null=True, verbose_name='Событие'),
        ),
    ]
